// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdDZ31guMBsbxHk4NZBaXxEnkP-CSb9dA',
    appId: '1:283551460018:web:57054cbd8c7aecf6c737ab',
    messagingSenderId: '283551460018',
    projectId: 'eventfi-app-1f365',
    authDomain: 'eventfi-app-1f365.firebaseapp.com',
    storageBucket: 'eventfi-app-1f365.firebasestorage.app',
    measurementId: 'G-KWWS1BKYRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJa-FkhAmNFMILT8JoPC-L3ap6ae2UzaI',
    appId: '1:283551460018:android:09d74f01135df828c737ab',
    messagingSenderId: '283551460018',
    projectId: 'eventfi-app-1f365',
    storageBucket: 'eventfi-app-1f365.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbYFu6PrlBVOMms1J9AQFv6RyyA_tZQmA',
    appId: '1:283551460018:ios:73bf85c88dd8488dc737ab',
    messagingSenderId: '283551460018',
    projectId: 'eventfi-app-1f365',
    storageBucket: 'eventfi-app-1f365.firebasestorage.app',
    iosClientId: '283551460018-rrulkiss7ekd93bvim9sd4bl5703q6jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventfiApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbYFu6PrlBVOMms1J9AQFv6RyyA_tZQmA',
    appId: '1:283551460018:ios:73bf85c88dd8488dc737ab',
    messagingSenderId: '283551460018',
    projectId: 'eventfi-app-1f365',
    storageBucket: 'eventfi-app-1f365.firebasestorage.app',
    iosClientId: '283551460018-rrulkiss7ekd93bvim9sd4bl5703q6jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventfiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdDZ31guMBsbxHk4NZBaXxEnkP-CSb9dA',
    appId: '1:283551460018:web:7802c86a66142e83c737ab',
    messagingSenderId: '283551460018',
    projectId: 'eventfi-app-1f365',
    authDomain: 'eventfi-app-1f365.firebaseapp.com',
    storageBucket: 'eventfi-app-1f365.firebasestorage.app',
    measurementId: 'G-71NSRZ1LNW',
  );
}
