require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Event = require('../models/Event');

const events = [
  // ─── CONCERTS ────────────────────────────────────────────────
  {
    title:       'AR Rahman Tribute Night',
    category:    'concert',
    description: 'A spectacular evening celebrating the music of AR Rahman. Featuring 12 live artists performing iconic hits across three decades — from Roja to Ponniyin Selvan.',
    city:        'Chennai',
    district:    'Chennai',
    venue:       'YMCA Ground, Nandanam',
    posterUrl:   'https://picsum.photos/seed/ev1/400/200',
    date:        new Date('2026-07-25'),
    time:        '7:00 PM',
    price:       799,
    totalSeats:  500,
    availableSeats: 342,
    latitude:    13.0415, longitude: 80.2602,
    organizerName: 'Chennai Live Events Pvt Ltd',
    organizerPhone: '+91 98400 11234',
    bookingCount: 158,
  },
  {
    title:       'Madurai Rock Fest 2026',
    category:    'concert',
    description: 'South India\'s biggest rock festival returns to Madurai. Three stages, six bands, one unforgettable night at Tamukkam Grounds.',
    city:        'Madurai',
    district:    'Madurai',
    venue:       'Tamukkam Grounds',
    posterUrl:   'https://picsum.photos/seed/ev2/400/200',
    date:        new Date('2026-08-03'),
    time:        '6:00 PM',
    price:       599,
    totalSeats:  800,
    availableSeats: 521,
    latitude:    9.9252, longitude: 78.1198,
    organizerName: 'South Rock Events',
    organizerPhone: '+91 94400 22345',
    bookingCount: 279,
  },
  {
    title:       'Pondy Fusion Night',
    category:    'concert',
    description: 'Jazz, Carnatic, and French café music merge into one magical evening along the Promenade. Featuring Aruna Sairam and local artists.',
    city:        'Puducherry',
    district:    'Puducherry',
    venue:       'Goubert Avenue Promenade',
    posterUrl:   'https://picsum.photos/seed/ev3/400/200',
    date:        new Date('2026-08-10'),
    time:        '7:30 PM',
    price:       449,
    totalSeats:  300,
    availableSeats: 187,
    latitude:    11.9416, longitude: 79.8083,
    organizerName: 'Pondy Arts Foundation',
    organizerPhone: '+91 98300 33456',
    bookingCount: 113,
  },

  // ─── THEATRE ─────────────────────────────────────────────────
  {
    title:       'Nataka Thiruvizha 2026',
    category:    'theatre',
    description: 'Chennai\'s premier drama festival returns with 8 original Tamil plays over 4 days. Featuring award-winning theatre groups from across Tamil Nadu.',
    city:        'Chennai',
    district:    'Chennai',
    venue:       'Narada Gana Sabha, T.Nagar',
    posterUrl:   'https://picsum.photos/seed/ev4/400/200',
    date:        new Date('2026-07-18'),
    time:        '6:30 PM',
    price:       249,
    totalSeats:  350,
    availableSeats: 204,
    latitude:    13.0418, longitude: 80.2341,
    organizerName: 'Chennai Drama Academy',
    organizerPhone: '+91 99400 44567',
    bookingCount: 146,
  },
  {
    title:       'Coimbatore Nataka Vizha',
    category:    'theatre',
    description: 'Three-day theatre festival showcasing Coimbatore\'s finest drama companies. Includes classical Tamil plays and modern experimental theatre.',
    city:        'Coimbatore',
    district:    'Coimbatore',
    venue:       'Town Hall Auditorium',
    posterUrl:   'https://picsum.photos/seed/ev5/400/200',
    date:        new Date('2026-08-05'),
    time:        '5:00 PM',
    price:       199,
    totalSeats:  400,
    availableSeats: 312,
    latitude:    11.0168, longitude: 76.9558,
    organizerName: 'Kovai Nataka Mandram',
    organizerPhone: '+91 97400 55678',
    bookingCount: 88,
  },
  {
    title:       'Vellore Fort Heritage Drama',
    category:    'theatre',
    description: 'An immersive open-air historical drama set within the 16th-century Vellore Fort. Tells the story of the Nayak kings through dance, drama, and light.',
    city:        'Vellore',
    district:    'Vellore',
    venue:       'Vellore Fort Grounds',
    posterUrl:   'https://picsum.photos/seed/ev6/400/200',
    date:        new Date('2026-08-15'),
    time:        '6:00 PM',
    price:       149,
    totalSeats:  600,
    availableSeats: 489,
    latitude:    12.9165, longitude: 79.1325,
    organizerName: 'Vellore Heritage Trust',
    organizerPhone: '+91 96400 66789',
    bookingCount: 111,
  },

  // ─── STANDUP ─────────────────────────────────────────────────
  {
    title:       'Kumar Varun Live in Chennai',
    category:    'standup',
    description: 'National award-winning comedian Kumar Varun brings his sold-out "Semma Tension" tour to Chennai. Two hours of pure laughs — Tamil and English.',
    city:        'Chennai',
    district:    'Chennai',
    venue:       'Sathyam Cinemas, Royapettah',
    posterUrl:   'https://picsum.photos/seed/ev7/400/200',
    date:        new Date('2026-07-20'),
    time:        '7:00 PM',
    price:       499,
    totalSeats:  250,
    availableSeats: 67,
    latitude:    13.0550, longitude: 80.2617,
    organizerName: 'Chennai Comedy Club',
    organizerPhone: '+91 95400 77890',
    bookingCount: 183,
  },
  {
    title:       'Trichy Sirippu Vizha',
    category:    'standup',
    description: 'Four popular YouTube comedians perform live at Grand Hotel Trichy. Expect relatable Tamil family humor, IT job jokes, and Chennai traffic rants.',
    city:        'Trichy',
    district:    'Trichy',
    venue:       'Grand Hotel Banquet Hall',
    posterUrl:   'https://picsum.photos/seed/ev8/400/200',
    date:        new Date('2026-07-30'),
    time:        '7:30 PM',
    price:       299,
    totalSeats:  200,
    availableSeats: 143,
    latitude:    10.7905, longitude: 78.7047,
    organizerName: 'Trichy Laughs Productions',
    organizerPhone: '+91 94300 88901',
    bookingCount: 57,
  },
  {
    title:       'Chennai Comedy Marathon',
    category:    'standup',
    description: 'Five comedians, five hours, zero filter. The Chennai Comedy Marathon is back — the longest stand-up show in South India. Includes intermission and snacks.',
    city:        'Chennai',
    district:    'Chennai',
    venue:       'Escapism, Anna Nagar',
    posterUrl:   'https://picsum.photos/seed/ev9/400/200',
    date:        new Date('2026-08-08'),
    time:        '5:00 PM',
    price:       399,
    totalSeats:  180,
    availableSeats: 102,
    latitude:    13.0850, longitude: 80.2101,
    organizerName: 'Comedy House India',
    organizerPhone: '+91 93300 99012',
    bookingCount: 78,
  },

  // ─── DANCE ────────────────────────────────────────────────────
  {
    title:       'Bharatanatyam Arangetram',
    category:    'dance',
    description: 'The grand debut performance of Kavya Krishnamurthy under the guidance of Guru Padma Subramaniam. A 3-hour classical Bharatanatyam recital at Narada Gana Sabha.',
    city:        'Chennai',
    district:    'Chennai',
    venue:       'Narada Gana Sabha, Alwarpet',
    posterUrl:   'https://picsum.photos/seed/ev10/400/200',
    date:        new Date('2026-07-22'),
    time:        '5:00 PM',
    price:       199,
    totalSeats:  400,
    availableSeats: 278,
    latitude:    13.0320, longitude: 80.2535,
    organizerName: 'Kalakshetra Foundation',
    organizerPhone: '+91 44 2491 1169',
    bookingCount: 122,
  },
  {
    title:       'Salem Kalaivizha Dance Fest',
    category:    'dance',
    description: 'A two-day classical and folk dance festival celebrating Tamil Nadu\'s rich dance heritage. Features Bharatanatyam, Kuchipudi, Kolatam, and Karakattam.',
    city:        'Salem',
    district:    'Salem',
    venue:       'Salem District Cultural Hall',
    posterUrl:   'https://picsum.photos/seed/ev11/400/200',
    date:        new Date('2026-08-02'),
    time:        '4:00 PM',
    price:       150,
    totalSeats:  300,
    availableSeats: 241,
    latitude:    11.6643, longitude: 78.1460,
    organizerName: 'Salem Cultural Foundation',
    organizerPhone: '+91 97800 10123',
    bookingCount: 59,
  },
  {
    title:       'Karagattam & Folk Night Madurai',
    category:    'dance',
    description: 'An authentic Karagattam folk performance featuring Madurai\'s most celebrated folk artists. Experience the vibrant colors, music, and energy of traditional Tamil folk culture.',
    city:        'Madurai',
    district:    'Madurai',
    venue:       'Meenakshi Amman Temple Grounds',
    posterUrl:   'https://picsum.photos/seed/ev12/400/200',
    date:        new Date('2026-08-12'),
    time:        '3:00 PM',
    price:       99,
    totalSeats:  1000,
    availableSeats: 834,
    latitude:    9.9195, longitude: 78.1193,
    organizerName: 'Madurai Folk Arts Trust',
    organizerPhone: '+91 96800 20234',
    bookingCount: 166,
  },

  // ─── THEME PARKS ──────────────────────────────────────────────
  {
    title:       'Dreamland Theme Park Chennai',
    category:    'themePark',
    description: 'South India\'s largest theme park with 40+ rides, 4 water slides, a kids\' zone, food court, and evening laser show. Perfect for families and groups.',
    city:        'Chennai',
    district:    'Kanchipuram',
    venue:       'Old Mahabalipuram Road, Sholinganallur',
    posterUrl:   'https://picsum.photos/seed/ev13/400/200',
    date:        new Date('2026-07-15'),
    time:        '9:00 AM',
    price:       699,
    totalSeats:  2000,
    availableSeats: 1456,
    latitude:    12.9010, longitude: 80.2279,
    organizerName: 'Dreamland Amusements Pvt Ltd',
    organizerPhone: '+91 44 6681 2200',
    bookingCount: 544,
  },
  {
    title:       'Fun Valley Coimbatore',
    category:    'themePark',
    description: 'Adventure park with 25 thrilling rides, wave pool, rain dance, paintball, and a separate zone for toddlers. Open all week. Combo packages available.',
    city:        'Coimbatore',
    district:    'Coimbatore',
    venue:       'Avinashi Road, Peelamedu',
    posterUrl:   'https://picsum.photos/seed/ev14/400/200',
    date:        new Date('2026-07-15'),
    time:        '9:30 AM',
    price:       499,
    totalSeats:  1500,
    availableSeats: 1189,
    latitude:    11.0400, longitude: 77.0200,
    organizerName: 'Fun Valley Parks Pvt Ltd',
    organizerPhone: '+91 97800 30345',
    bookingCount: 311,
  },
  {
    title:       'Adventure Kingdom Trichy',
    category:    'themePark',
    description: 'Central Tamil Nadu\'s premier family entertainment park. Featuring 20 rides, a mini zoo, 3D cinema, food street, and night illumination show on weekends.',
    city:        'Trichy',
    district:    'Trichy',
    venue:       'Srirangam Ring Road',
    posterUrl:   'https://picsum.photos/seed/ev15/400/200',
    date:        new Date('2026-07-15'),
    time:        '10:00 AM',
    price:       399,
    totalSeats:  1200,
    availableSeats: 987,
    latitude:    10.8500, longitude: 78.6800,
    organizerName: 'Adventure Kingdom Pvt Ltd',
    organizerPhone: '+91 96700 40456',
    bookingCount: 213,
  },
];

const seed = async () => {
  try {
    await connectDB();
    await Event.deleteMany({});
    const created = await Event.insertMany(events);
    console.log(`✅ Seeded ${created.length} Tamil Nadu events`);
    created.forEach(e => console.log(`   • [${e.category.padEnd(10)}] ${e.title} — ₹${e.price} — ${e.city}`));
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
  } finally {
    process.exit(0);
  }
};

seed();
